module.exports.restaurantNames = [
    "SavorScape",
    "FlavorFusion",
    "TasteTrail",
    "PalateParadise",
    "GastronomyGrove",
    "EpicureanEden",
    "CuisineCove",
    "FeastFrontier",
    "FlavorsomeHaven",
    "GourmetGateway",
    "TastyTrove",
    "DineDelight",
    "SensorySafari",
    "EatsEmporium",
    "EpicEatery",
    "DelishDomain",
    "GustatoryGarden",
    "EatableOasis",
    "FlavorField",
    "TastefulTerrace",
    "TasteBoulevard",
    "EpicureEmpire",
    "GourmetGrove",
    "DeliciousDomain",
    "SavorSanctuary"
  ];

